# Current Version: 1.0.6

name: Build & Release hezhijie0327/DockerimageBuilder (Base)

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    build-base-alpine:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build base:alpine
              uses: docker/build-push-action@v5
              with:
                  file: ./base/alpine.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/base:alpine
