# Current Version: 1.0.1

name: Build & Push hezhijie0327/DockerimageBuilder/base

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 0 * * *"

jobs:
    build-alpine:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build base:alpine
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./base/alpine.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/base:alpine
    build-sshd:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build base:sshd
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./base/sshd.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/base:sshd
    build-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build base:ubuntu
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./base/ubuntu.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/base:ubuntu
