# Current Version: 1.0.3

name: Build & Push hezhijie0327/DockerimageBuilder

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 0 * * *"

jobs:
    build-adguardhome:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v2.3.4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.0.1
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.1.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.8.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build adguardhome:latest
              uses: docker/build-push-action@v2.2.2
              with:
                  file: ./adguardhome.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/adguardhome:latest
    build-aria2:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v2.3.4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.0.1
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.1.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.8.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build aria2:latest
              uses: docker/build-push-action@v2.2.2
              with:
                  file: ./aria2.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/aria2:latest
