# Current Version: 1.0.0

name: Build & Push hezhijie0327/DockerimageBuilder/module

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 0 * * *"

jobs:
    build-cares:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:cares
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/cares.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:cares
    build-expat:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:expat
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/expat.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:expat
    build-golang:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:golang
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/golang.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:golang
    build-gperftools:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:gperftools
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/gperftools.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:gperftools
    build-libssh2:
        needs: build-openssl
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:libssh2
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/libssh2.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:libssh2
    build-libuv:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:libuv
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/libuv.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:libuv
    build-nodejs:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:nodejs
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/nodejs.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:nodejs
    build-openssl:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:openssl
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/openssl.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:openssl
    build-sqlite:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:sqlite
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/sqlite.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:sqlite
    build-zlibng:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.0.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v1.2.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v1.6.0
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v1.10.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:zlibng
              uses: docker/build-push-action@v2.10.0
              with:
                  file: ./module/zlibng.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:zlibng
