# Current Version: 1.0.0

name: Build & Release hezhijie0327/DockerimageBuilder (Module)

on:
    schedule:
        - cron: "0 8 * * *"
    workflow_dispatch:

jobs:
    build-binary-dotnet:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:binary-dotnet
              uses: docker/build-push-action@v5
              with:
                  file: ./module/binary-dotnet.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:binary-dotnet
    build-binary-golang:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:binary-golang
              uses: docker/build-push-action@v5
              with:
                  file: ./module/binary-golang.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:binary-golang
    build-binary-nodejs:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:binary-nodejs
              uses: docker/build-push-action@v5
              with:
                  file: ./module/binary-nodejs.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:binary-nodejs
    build-binary-rust:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:binary-rust
              uses: docker/build-push-action@v5
              with:
                  file: ./module/binary-rust.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:binary-rust
    build-glibc-cares:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-cares
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-cares.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-cares
    build-glibc-expat:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-expat
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-expat.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-expat
    build-glibc-gperftools:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-gperftools
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-gperftools.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-gperftools
    build-glibc-jemalloc:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-jemalloc
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-jemalloc.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-jemalloc
    build-glibc-libevent:
        needs: [build-glibc-openssl]
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-libevent
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-libevent.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-libevent
    build-glibc-libhiredis:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-libhiredis
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-libhiredis.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-libhiredis
    build-glibc-libmnl:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-libmnl
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-libmnl.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-libmnl
    build-glibc-libsodium:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-libsodium
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-libsodium.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-libsodium
    build-glibc-libssh2:
        needs: [build-glibc-openssl]
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-libssh2
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-libssh2.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-libssh2
    build-glibc-libuv:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-libuv
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-libuv.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-libuv
    build-glibc-libnghttp2:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-libnghttp2
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-libnghttp2.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-libnghttp2
    build-glibc-lua:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-lua
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-lua.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-lua
    build-glibc-openssl:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-openssl
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-openssl.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-openssl
    build-glibc-pcre2:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-pcre2
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-pcre2.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-pcre2
    build-glibc-sqlite:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-sqlite
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-sqlite.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-sqlite
    build-glibc-zlibng:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:glibc-zlibng
              uses: docker/build-push-action@v5
              with:
                  file: ./module/glibc-zlibng.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:glibc-zlibng
