# Current Version: 1.1.3

name: Build & Release hezhijie0327/DockerimageBuilder (Module)

on:
    schedule:
        - cron: "0 8 * * *"
    workflow_dispatch:

jobs:
    build-module-dotnet:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:dotnet
              uses: docker/build-push-action@v5
              with:
                  file: ./module/dotnet.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:dotnet
    build-module-expat:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:expat
              uses: docker/build-push-action@v5
              with:
                  file: ./module/expat.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:expat
    build-module-libevent:
        needs: [build-module-openssl]
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:libevent
              uses: docker/build-push-action@v5
              with:
                  file: ./module/libevent.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:libevent
    build-module-libhiredis:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:libhiredis
              uses: docker/build-push-action@v5
              with:
                  file: ./module/libhiredis.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:libhiredis
    build-module-libmnl:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:libmnl
              uses: docker/build-push-action@v5
              with:
                  file: ./module/libmnl.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:libmnl
    build-module-libsodium:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:libsodium
              uses: docker/build-push-action@v5
              with:
                  file: ./module/libsodium.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:libsodium
    build-module-libnghttp2:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:libnghttp2
              uses: docker/build-push-action@v5
              with:
                  file: ./module/libnghttp2.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:libnghttp2
    build-module-nodejs:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:nodejs
              uses: docker/build-push-action@v5
              with:
                  file: ./module/nodejs.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:nodejs
    build-module-openssl:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:openssl
              uses: docker/build-push-action@v5
              with:
                  file: ./module/openssl.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:openssl
    build-module-rust:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build module:rust
              uses: docker/build-push-action@v5
              with:
                  file: ./module/rust.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/module:rust
