# Current Version: 1.2.6

name: Build & Push hezhijie0327/DockerimageBuilder/repo

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 0 * * *"

jobs:
    build-adguardhome:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build adguardhome:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/adguardhome.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/adguardhome:latest
    build-aria2:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build aria2:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/aria2.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/aria2:latest
    build-clash:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build clash:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/clash.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/clash:latest
    build-dnsproxy:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build dnsproxy:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/dnsproxy.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/dnsproxy:latest
    build-jellyfin:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build jellyfin:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/jellyfin.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/jellyfin:latest
    build-mosdns:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build mosdns:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/mosdns.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/mosdns:latest
    build-qbittorrent:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build qbittorrent:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/qbittorrent.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/qbittorrent:latest
    build-unbound:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build unbound:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/unbound.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/unbound:latest
    build-vlmcsd:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.2.1
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v2.1.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Build vlmcsd:latest
              uses: docker/build-push-action@v3.2.0
              with:
                  file: ./repo/vlmcsd.dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/vlmcsd:latest
